### ISSUE TITLE
"GlyphLessFont" error when opening PDF

### ISSUE THREAD

**Issue by rmtheis** [rmtheis/tess-two#104]
Error when opening a PDF generated with tess-two using Adobe Reader 11:

    Cannot extract the embedded font 'GlyphLessFont'. Some characters may not display or print correctly.

**Comment by rmtheis** [comment]
https://groups.google.com/forum/?fromgroups#!topic/tesseract-dev/xXplYPiZCZI

**Comment by rmtheis** [comment]
To fix this, the pdf.ttf file from tesseract's tessdata directory must be present in the device's tessdata directory.

**Comment by ArjanSchouten** [comment]
There is a pdf.ttf file and a pdf.ttx file. Do I need both or only pdf.ttf?

**Comment by rmtheis** [comment]
Using only pdf.ttf seems to always work for me, but you might want to ask on the Tesseract mailing list to be sure.

**Comment by ArjanSchouten** [comment]
Thanks for your reaction! Already used only pdf.ttf since pdfrenderer is only referencing that one in the source.

However I got the error "Expected a name object" in Adobe Reader. I read somewhere that this could be due to wrong fonts. Therefore I was wondering about that file.

@rmtheis Have you ever got "There was a problem reading this document (18)" and by pressing ctrl - OK "Expected a name object"?

**Comment by rmtheis** [comment]
Hmm, no. Could be a bug in Tesseract.

**Comment by ArjanSchouten** [comment]
Yeah I think so. If I can't fix it I will create an issue at tesseract-ocr. Thanks.
