### ISSUE TITLE
Using Github Releases for binary releases

### ISSUE THREAD

**Issue by stephengroat** [rmtheis/tess-two#120]
Wondering if there's ever been any consideration to using Github Releases for binary releases of tess-two and eyes-two. With the current state of ndk integration in Android, a compiled and import-able module for Android Studio would be nice.

I'm still new to Gradle and trying to deal with a bunch of NDK issues, but I'd be willing to help wherever I can

**Comment by rmtheis** [comment]
I agree that a simpler, Android Studio-based integration is needed. I'd really like to get help with getting the proposed Gradle build (#99) working with the experimental plugin so that the NDK build would fire off from within Android Studio. That would eliminate having to do a separate command-line build at all.

**Comment by rmtheis** [comment]
Any thoughts on whether Jitpack would be a good tool for this project?

**Comment by Kadrei** [comment]
I don't know if tess-two as a gradle dependency via jitpack is the best possibility, because as far as i know it does not work with [ABIs Splits](http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits) which is a huge improvement for the download size of an apk using tess-two. A simple   Release-zip which has compiled .aar's for the main ABIs ('x86', 'armeabi-v7a', 'mips') might be better.

**Comment by rmtheis** [comment]
Thanks for the feedback. Let's track this on #99.
