### ISSUE TITLE
Recognition time deadline - set_deadline_msecs()

### ISSUE THREAD

**Issue by crafter** [rmtheis/tess-two#137]
I have a problem with tesseract recognition time in android, it's taking too long time to recognize text. 
In ios it has a function to give tesseract max recognition time like `tesseract.maximumRecognitionTime = 60.0`. Is there any way to give tesseract maximum recognition time in android like ios?

http://stackoverflow.com/questions/35501125/tesseract-max-recognition-time-in-android

**Comment by rmtheis** [comment]
This is best implemented directly by the apps using this API, because they already handle the launching of Tesseract's long-running operations on separate threads.

So your best bet is to create your own timer and call the `stop` method when you hit your deadline.

For an example of calling `stop`, see the `testStop` test case.
