### ISSUE TITLE
no field with name='mNativeData' signature='J' in class Lcom/googlecode/tesseract/android/TessBaseAPI;

### ISSUE THREAD

**Issue by schrieveslaach** [rmtheis/tess-two#166]
I'm trying to create `TessBaseAPI` on a Nexus 7 with Cyanogenmod 11 (Android 4.4.4). When the constructor gets called I get an exception:

    java.lang.NoSuchFieldError: no field with name='mNativeData' signature='J' in class Lcom/googlecode/tesseract/android/TessBaseAPI;
        at com.googlecode.tesseract.android.TessBaseAPI.nativeClassInit(Native Method)
        at com.googlecode.tesseract.android.TessBaseAPI.<clinit>(TessBaseAPI.java:48)

Do you have any ideas?

**Comment by schrieveslaach** [comment]
OK, I found the issue.  It was related to proguard. Maybe you can add an example proguard configuration file to the README.md. Here is mine:

    -dontwarn com.googlecode.tesseract.**
    -keep class com.googlecode.tesseract.** {
        *;
    }

**Comment by rmtheis** [comment]
There's already a [Proguard config file](https://github.com/rmtheis/tess-two/blob/ecb4219ceaa1dba01a834102e3275fce2996ffed/tess-two/proguard-rules.pro) but apparently your project setup didn't pick it up.

I want to see if using `consumerProguardFiles` instead of `proguardFiles` in the build.gradle for this project helps the situation. Needs investigation.
