### ISSUE TITLE
In versions higher than 5.4.1 TessBaseAPI.ProgressNotifier never called

### ISSUE THREAD

**Issue by lonelyfugitive** [rmtheis/tess-two#262]
Summary: After updating gradle dependency version higher than 5.4.1 the ProgressNotifier is triggered no more.

`tessBaseApi = TessBaseAPI(TessBaseAPI.ProgressNotifier { progressValues ->
            //this part isn't called on current version
            activity.showProgress("${activity.getString(R.string.recognising)} ${progressValues.percent}%")
        })`

Steps to reproduce the issue:

1. Add any photo
2. Start recognizing process

Expected result: percentage progress shown

Actual result:  UI changes isn't triggered by ProgressNotifier

Tess-two version: 6.0.0+

Android version: 7.0

Phone/device model: Xiaomi Redmi NOTE 4

Phone/device architecture: aarch64

Link to project:  [Github project MediOCR](https://github.com/lonelyfugitive/mediOCR/tree/master)

**Comment by rmtheis** [comment]
See [this note](https://github.com/rmtheis/tess-two/blob/ac415295cdbc202e258cedcf667268e5ae0e56f5/tess-two/src/com/googlecode/tesseract/android/TessBaseAPI.java#L178). You need to use `getHOCRText` [here](https://github.com/lonelyfugitive/mediOCR/blob/7515254068b8797171cb0a2bb050aa39ab39e6b0/app/src/main/kotlin/com/akimchenko/antony/mediocr/fragments/PreviewFragment.kt#L273) instead of `getUTF8Text`.
