### ISSUE TITLE
ReadFile.readBitmap alters image colors

### ISSUE THREAD

**Issue by rmtheis** [rmtheis/tess-two#87]
ReadFile.readFile and ReadFile.readMem seem to be changing white to gray.

**Comment by rmtheis** [comment]
On some devices, this is causing the following tests to fail in ReadFileTest:

testReadFile_jpg
testReadMem_jpg

**Comment by rmtheis** [comment]
![device-2015-06-02-072547](https://cloud.githubusercontent.com/assets/943135/7938154/e9b618a0-08f8-11e5-9f76-15fc9068a309.png)

**Comment by rmtheis** [comment]
The tests have been fixed but the ReadFile problems remain. The following tests are now failing:

testReadBitmap (the alpha value is apparently read incorrectly for the 1x1 bitmap)
testReadFile_jpg
testReadMem_jpg

**Comment by megabytefisher** [comment]
From my minor testing on this, I am wondering if these tests are failing because of "Java_com_googlecode_leptonica_android_ReadFile_nativeReadBitmap" converting the 32-bit bitmap image to a 8-bit grayscale image? The alpha data of the image is discarded, so I'm guessing the internal RGBA representation has an alpha value that is not equal to the full opaque value? I'm not totally sure.

I can do more testing on this issue, but in any case, would you be opposed to me modifying the aforementioned function so that it creates a Pix with the full 32-bit data, instead of grayscale?

The code I mentioned is here:
https://github.com/rmtheis/tess-two/blob/master/tess-two/jni/com_googlecode_leptonica_android/readfile.cpp#L113

**Comment by rmtheis** [comment]
I think changing the function to return a Pix with the full 32-bit data would be fine, and worth doing.

Yes it does look like the alpha data is currently discarded.

Hmm, it looks like there's a version in renard314's version of the repo that may be worth testing and using: https://github.com/renard314/tess-two/blob/master/tess-two/jni/com_googlecode_leptonica_android/readfile.cpp#L141

I see there's a function called `pixEndianByteSwap` in renard314's version. I seem to remember some endianness-related changes in the pre-release Leptonica code that may possibly perform a related function. I haven't taken a close look at either Renard's version or the Leptonica code at this point though.

**Comment by megabytefisher** [comment]
This did end up fixing all those failing tests- I used renard314's version. I hope that's okay.

**Comment by megabytefisher** [comment]
Actually, upon second look, this might have introduced another issue- I'm now getting:

com.googlecode.leptonica.android.test.JpegIOTest > testCompressToJpeg[XT907 - 4.4.2] FAILED
Test failed to run to completion. Reason: 'Instrumentation run failed due to 'Native crash''. Check device logcat for details
Tests on XT907 - 4.4.2 failed: Instrumentation run failed due to 'Native crash'
:tess-two-test:connectedDebugAndroidTest FAILED

Let me test this some more.

**Comment by alexcohn** [comment]
I have fixed this and similar WriteFile tests in [my fork](https://github.com/alexcohn/Tesseract4Android), which uses Tesseract 4.0. Should I create a special Pull Request for these changes, or maybe it would be wise to move the whole project to Tesseract 4.0 ?

**Comment by rmtheis** [comment]
My preference would be to first have pull requests or a single PR to fix this issue and the other similar issues, so that I could tag a release and publish a version on Bintray with those fixes for users who want to have the bug fixes but don't want to upgrade to Tesseract 4.0 yet.

**Comment by alexcohn** [comment]
Feel free to cherry-pick the relevant commits. Note that no changes to tesseract or leptronica sources were not involved.

I will be away from computers for about a week, but if you need my help I will do my best on return from this short vacation.

**Comment by alexcohn** [comment]
Feel free to cherry-pick the relevant commits. Note that no changes to tesseract or leptronica sources were not involved.

I will be away from computers for about a week, but if you need my help I will do my best on return from this short vacation.
